package envwriter

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// Write merges the provided secrets into the target .env file.
// Existing keys are updated; new keys are appended; unrelated keys are preserved.
func Write(filePath string, secrets map[string]string) error {
	existing, err := readEnvFile(filePath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("reading env file: %w", err)
	}

	for k, v := range secrets {
		existing[k] = v
	}

	return writeEnvFile(filePath, existing)
}

func readEnvFile(filePath string) (map[string]string, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return make(map[string]string), err
	}

	result := make(map[string]string)
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			result[parts[0]] = parts[1]
		}
	}
	return result, nil
}

func writeEnvFile(filePath string, data map[string]string) error {
	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Generated by vaultpull — do not edit manually\n")
	for _, k := range keys {
		fmt.Fprintf(&sb, "%s=%s\n", k, data[k])
	}

	return os.WriteFile(filePath, []byte(sb.String()), 0600)
}
